name: "Dump logs"
description: "Collects all charm and k8s logs"

runs:
  using: "composite"
  steps:
  - name: Dump debug log
    run: |
      for ctl in $(juju controllers --format json | jq -r '.controllers | keys[]'); do for mdl in $(juju models --format json | jq -r '.models[].name' | grep -v "admin/controller"); do juju debug-log -m $ctl:$mdl --replay --ms --no-tail; done; done || true
      exit 0
    shell: bash
  - name: Dump pods and their logs
    shell: bash
    run: |
      juju status --relations --storage
      kubectl get pods \
          -A \
          -o=jsonpath='{range.items[*]}{.metadata.namespace} {.metadata.name}{"\n"}' \
          --sort-by=.metadata.namespace \
          | grep -v "^\s*$" \
          | while read namespace pod; do \
               kubectl -n $namespace describe pod $pod; \
               kubectl -n $namespace logs $pod \
                  --all-containers=true \
                  --tail=100; \
           done
  - name: Dump deployments
    run: |
      kubectl describe deployments -A
      exit 0
    shell: bash
  - name: Dump replicasets
    run: |
      kubectl describe replicasets -A
      exit 0
    shell: bash
  - name: Dump node information
    run: |
      kubectl get nodes -v=10
      exit 0
    shell: bash
  - name: Dump charmcraft logs
    uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
    with:
      name: charmcraft-logs
      path: ~/.local/state/charmcraft/log/*.log
