name: CI

on:
  push:
    branches:
      - 'track/*'
      - 'main'
  pull_request:
    branches:
      - 'track/*'
      - 'main'

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          npm install
      - name: Execute tests
        run: |
          npm run test
  linting:
    runs-on: ubuntu-latest
    name: Linting
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          npm install
      - name: Lint
        run: |
          npm run format
          npm run lint
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run build

          if [[ -n "$(git status -s)" ]]; then
            echo "Please run 'npm run build' then commit/push changes"
            echo
            git diff
            exit 1
          fi
