name: CI

on:
  push:
    branches:
      - 'track/*'
      - 'main'
  pull_request:
    branches:
      - 'track/*'
      - 'main'

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 24
      - name: Install dependencies
        run: |
          npm install
      - name: Execute tests
        run: |
          npm run test
  linting:
    runs-on: ubuntu-latest
    name: Linting
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 24
      - name: Install dependencies
        run: |
          npm install
      - name: Lint
        run: |
          npm run format
          npm run lint
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 24
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run build

          if [[ -n "$(git status -s)" ]]; then
            echo "Please run 'npm run build' then commit/push changes"
            echo
            git diff
            exit 1
          fi
